spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: 123456
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:com/majianwei/plat/mapper/*Mapper.xml
  type-aliases-package: com.majianwei.plat.domain,com.majianwei.plat.query
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou_test
      username: root
      password: 123456
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:com/majianwei/plat/mapper/*Mapper.xml
  type-aliases-package: com.majianwei.plat.domain,com.majianwei.plat.query
