spring:
  profiles:
    active:
    - dev

---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/aigou"
  ignored-services: "*"
  routes:
    store.serviceId: plat-service
    store.path: /store/**

---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true
zuul:
  prefix: "/aigou"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-service
    plat.path: /store/**
